server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB # 单文件大小
      max-request-size: 1GB # 连续上传文件大小
app:
  repository: AppRepository
  ignore-files: # 忽略的文件将被删除
    auto-answer: # 被忽略的应用
      - __MACOSX
      - .DS_Store



